# Generated by Django 6.0.5 on 2026-05-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spotify', 'Spotify'), ('youtube_music', 'YouTube Music')], max_length=20)),
                ('url', models.URLField()),
                ('titulo', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enlace de Musica',
                'verbose_name_plural': 'Enlaces de Musica',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='SVG icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fuente de Noticias',
                'verbose_name_plural': 'Fuentes de Noticias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sesion de Trading',
                'verbose_name_plural': 'Sesiones de Trading',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Creemos Capital', max_length=200)),
                ('site_description', models.TextField(default='Trading en vivo con estrategia C4')),
                ('whatsapp_number', models.CharField(default='+57 315 326 3852', max_length=20)),
                ('whatsapp_url', models.URLField(default='https://wa.me/573153263852')),
                ('telegram_url', models.URLField(default='https://t.me/creemoscapitaloficial')),
                ('email', models.EmailField(default='info@creemoscapital.com', max_length=254)),
                ('kick_channel', models.CharField(default='creemoscapital', max_length=100)),
                ('youtube_channel', models.CharField(default='@creemoscapital', max_length=100)),
                ('youtube_channel_url', models.URLField(default='https://www.youtube.com/@creemoscapital')),
                ('google_form_url', models.URLField(default='https://forms.gle/gpwxCJwcXvEX2bU26')),
                ('okx_affiliate_url', models.URLField(default='https://www.okx.com/join/CREEMOS')),
                ('spotify_url', models.URLField(blank=True, default='')),
                ('youtube_music_url', models.URLField(blank=True, default='')),
                ('youtube_music_playlist_id', models.CharField(default='UUv4ma-yTMOqYYF_Ii5kv0zQ', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuracion del Sitio',
                'verbose_name_plural': 'Configuracion del Sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='SVG icon class or emoji', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('novatos', 'Trading para Novatos'), ('estrategia', 'La Estrategia')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['categoria', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SesionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', models.CharField(help_text='Paises separados por /', max_length=100)),
                ('bandera_codigo', models.CharField(help_text='Codigo de bandera (flagcdn)', max_length=5)),
                ('hora', models.CharField(max_length=50)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.sesion')),
            ],
            options={
                'verbose_name': 'Horario de Sesion',
                'verbose_name_plural': 'Horarios de Sesiones',
                'ordering': ['sesion__order', 'id'],
            },
        ),
    ]
