# Generated by Django 6.0.5 on 2026-05-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('master', 'Master'), ('member', 'Miembro de Comunidad')], default='member', max_length=20, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Teléfono WhatsApp')),
                ('telegram', models.CharField(help_text='Incluir @ si aplica', max_length=50, verbose_name='Usuario Telegram')),
                ('tiempo_interes', models.CharField(choices=[('menos_1mes', 'Menos de 1 mes'), ('1-6meses', '1 a 6 meses'), ('6-12meses', '6 a 12 meses'), ('1-2anos', '1 a 2 años'), ('mas_2anos', 'Más de 2 años')], max_length=20, verbose_name='¿Hace cuánto te interesa el trading?')),
                ('experiencia', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, verbose_name='Nivel de Experiencia')),
                ('mercados', models.CharField(help_text='Separados por coma', max_length=200, verbose_name='Mercados de Interés')),
                ('objetivo_principal', models.CharField(choices=[('ingresos_extra', 'Generar Ingresos Extra'), ('vivir_trading', 'Vivir del Trading'), ('aprender_cero', 'Aprender desde Cero'), ('lograr_consistencia', 'Lograr Consistencia'), ('cuenta_fondeo', 'Para una Cuenta de Fondeo'), ('otro', 'Otro')], max_length=20, verbose_name='Objetivo Principal')),
                ('objetivo_otro', models.CharField(blank=True, max_length=200, verbose_name='Otro Objetivo')),
                ('capital', models.CharField(choices=[('0-100', '$0 - $100 USD'), ('100-1000', '$100 - $1,000 USD'), ('1000-5000', '$1,000 - $5,000 USD'), ('5000+', 'Más de $5,000 USD')], max_length=20, verbose_name='Capital para Operar')),
                ('mayor_dificultad', models.CharField(choices=[('no_se_por_donde', 'No sé por dónde empezar'), ('pierdo_dinero', 'Pierdo dinero constantemente'), ('falta_disciplina', 'Falta de disciplina'), ('no_entiendo', 'No entiendo el mercado'), ('mala_gestion', 'Mala gestión de riesgo'), ('otro', 'Otro')], max_length=20, verbose_name='Mayor Dificultad')),
                ('dificultad_otro', models.CharField(blank=True, max_length=200, verbose_name='Otra Dificultad')),
                ('plataformas', models.CharField(help_text='Separados por coma', max_length=200, verbose_name='Plataformas de Trading')),
                ('plataforma_otro', models.CharField(blank=True, max_length=200, verbose_name='Otra Plataforma')),
                ('contenido_interes', models.CharField(help_text='Separados por coma', max_length=200, verbose_name='Contenido de Interés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['-created_at'],
            },
        ),
    ]
