# Generated by Django 6.0.5 on 2026-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='acepta_terminos',
            field=models.BooleanField(default=False, verbose_name='Aceptación de Términos'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='broker_actual',
            field=models.CharField(blank=True, choices=[('okx', 'OKX'), ('fxpro', 'FXPRO'), ('tickmill', 'Tickmill'), ('pepperstone', 'Pepperstone'), ('exness', 'Exness'), ('bybit', 'Bybit'), ('otro', 'Otro')], max_length=20, verbose_name='¿Cuál utilizas actualmente?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='broker_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Otro Broker'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documento o Selfie'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='interesado_eventos',
            field=models.BooleanField(default=False, verbose_name='¿Te interesan eventos presenciales o virtuales?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='interesado_herramientas',
            field=models.BooleanField(default=False, verbose_name='¿Te gustaría operar con herramientas y brokers recomendados?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='interesado_ofertas',
            field=models.BooleanField(default=False, verbose_name='¿Te gustaría recibir ofertas exclusivas, promociones o lanzamientos?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='interesado_sesiones_vivo',
            field=models.BooleanField(default=False, verbose_name='¿Te gustaría participar activamente en sesiones en vivo?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='opera_broker',
            field=models.BooleanField(default=False, verbose_name='¿Actualmente operas con algún broker o exchange?'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='referral_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Otra Fuente'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('amigo', 'Recomendación de un amigo'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('otro', 'Otro')], default='', max_length=20, verbose_name='¿Por dónde te enteraste de Creemos Capital?'),
        ),
    ]
