# Generated by Django 6.0.5 on 2026-05-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_miembro_acepta_terminos_miembro_broker_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Operación')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('par', models.CharField(help_text='Ej: EURUSD, BTCUSDT, XAUUSD', max_length=20, verbose_name='Par/Activo')),
                ('mercado', models.CharField(choices=[('forex', 'Forex'), ('cripto', 'Criptomonedas'), ('indices', 'Índices'), ('materias_primas', 'Materias Primas'), ('acciones', 'Acciones')], max_length=20, verbose_name='Mercado')),
                ('tipo', models.CharField(choices=[('long', 'Long (Compra)'), ('short', 'Short (Venta)')], max_length=10, verbose_name='Tipo de Operación')),
                ('estrategia', models.CharField(choices=[('c4', 'Estrategia C4'), ('soporte_resistencia', 'Soporte/Resistencia'), ('fibonacci', 'Fibonacci'), ('ict', 'ICT/SMC'), ('otro', 'Otro')], max_length=30, verbose_name='Estrategia')),
                ('estrategia_otro', models.CharField(blank=True, max_length=100, verbose_name='Otra Estrategia')),
                ('precio_entrada', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Precio de Entrada')),
                ('precio_salida', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Precio de Salida')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Take Profit')),
                ('lotes', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Lotes/Tamaño')),
                ('resultado', models.CharField(choices=[('ganancia', 'Ganancia'), ('perdida', 'Pérdida'), ('breakeven', 'Breakeven'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15, verbose_name='Resultado')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia o pérdida en dólares', max_digits=12, null=True, verbose_name='P&L ($)')),
                ('pnl_porciento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia/pérdida', max_digits=6, null=True, verbose_name='P&L (%)')),
                ('rr', models.DecimalField(blank=True, decimal_places=2, help_text='Ratio Riesgo/Beneficio', max_digits=5, null=True, verbose_name='Risk:Reward')),
                ('duracion', models.CharField(blank=True, help_text='Ej: 2h 30min', max_length=20, verbose_name='Duración')),
                ('emocion', models.CharField(blank=True, choices=[('confiado', 'Confiado'), ('neutral', 'Neutral'), ('ansioso', 'Ansioso'), ('miedo', 'Miedo'), ('codicia', 'Codicia'), ('impulsivo', 'Impulsivo'), ('disciplinado', 'Disciplinado')], max_length=15, verbose_name='Emoción durante el trade')),
                ('notas', models.TextField(blank=True, verbose_name='Notas y Observaciones')),
                ('lecciones', models.TextField(blank=True, verbose_name='Lecciones Aprendidas')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='trades/screenshots/', verbose_name='Captura de Pantalla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.miembro')),
            ],
            options={
                'verbose_name': 'Registro de Trading',
                'verbose_name_plural': 'Bitácora de Trading',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['miembro', 'fecha'], name='core_tradej_miembro_d347ca_idx'), models.Index(fields=['miembro', 'resultado'], name='core_tradej_miembro_7143f0_idx')],
            },
        ),
    ]
