# Generated by Django 6.0.5 on 2026-05-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tradejournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradejournal',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Registro Manual'), ('okx_api', 'OKX API'), ('okx_csv', 'OKX CSV')], default='manual', max_length=15, verbose_name='Fuente de Registro'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='okx_order_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='OKX Order ID'),
        ),
        migrations.CreateModel(
            name='OKXApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=200, verbose_name='API Secret')),
                ('passphrase', models.CharField(max_length=200, verbose_name='Passphrase')),
                ('is_active', models.BooleanField(default=False, verbose_name='Conexión Activa')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='okx_config', to='core.miembro')),
            ],
            options={
                'verbose_name': 'Configuración OKX API',
                'verbose_name_plural': 'Configuraciones OKX API',
            },
        ),
    ]
