# Generated by Django 6.0.5 on 2026-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tradejournal_fuente_tradejournal_okx_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okxapiconfig',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Balance Total (USD)'),
        ),
        migrations.AddField(
            model_name='okxapiconfig',
            name='account_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalles de Cuenta'),
        ),
        migrations.AddField(
            model_name='okxapiconfig',
            name='okx_uid',
            field=models.CharField(blank=True, max_length=50, verbose_name='OKX UID'),
        ),
        migrations.AddField(
            model_name='okxapiconfig',
            name='total_trades_api',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Trades en OKX'),
        ),
        migrations.AddField(
            model_name='okxapiconfig',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Volumen Total Tradeado'),
        ),
    ]
